### Get Orion Entities
GET http://localhost:1026/v2/entities

### Device entities at models service and flowers service-path
GET http://localhost:1026/v2/entities
fiware-service: models
fiware-servicepath: /flowers

### Devices defined at production service and manufacturer service-path
GET http://localhost:4041/iot/devices
fiware-service: models
fiware-servicepath: /flowers

### Check IoT Agent Services for the models service and any (*) service-path
GET http://localhost:4041/iot/services
fiware-service: models
fiware-servicepath: /*

### Orion subscriptions
GET http://localhost:1026/v2/subscriptions

### Issue a listModels command to the classifier device through Orion
PATCH http://localhost:1026/v2/entities/urn:ngsi-ld:ImageClassifier:001/attrs
Content-Type: application/json
fiware-service: models
fiware-servicepath: /flowers

{
    "listModels": {
        "type": "command",
        "value": ""
    }
}

### Classifier entity
GET http://localhost:1026/v2/entities/urn:ngsi-ld:ImageClassifier:001
fiware-service: models
fiware-servicepath: /flowers

### Issue a model selection command to the classifier through Orion
POST http://localhost:1026/v2/op/update
Content-Type: application/json
fiware-service: models
fiware-servicepath: /flowers

{
    "actionType": "update",
    "entities": [
        {
            "id": "urn:ngsi-ld:ImageClassifier:001",
            "type": "classifier",
            "selectModel": {
                "type": "command",
                "value": "flowers_model.zip"
            }
        }
    ]
}

### Issue a capture command to the camera device through Orion
PATCH http://localhost:1026/v2/entities/urn:ngsi-ld:Camera:001/attrs
Content-Type: application/json
fiware-service: production
fiware-servicepath: /manufacturer

{
    "capture": {
        "type": "command",
        "value": ""
    }
}
